language: ruby
rvm:
  - 1.27.0
env:
  - DB=postgresql
addons:
  postgresql: "9.5.4:"
script:
  - bundle install
  - bundle exec rake db:setup
  - RAILS_ENV=test bundle exec rake db:seed
  - bundle exec rake
before_script:
  - cp config/database.yml.travis config/database.yml

